### ISSUE TITLE
FAQ- linktree link fix

### ISSUE THREAD

**Issue by boradesanket13** [SOS-TECH-Inc/SOS-TECH-Inc.github.io#4]
FAQ- linktree link in FAQ isn't clickable
![Screenshot (1269)](https://user-images.githubusercontent.com/79108273/213910153-5fbe1790-9151-4cf6-9022-2e4ee8d9d88f.png)

**Comment by mr-hingolja** [comment]
Ok i take it to resolve.

**Comment by Divjot121** [comment]
Thanks
